export const state = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamilnadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "UttraKhand",
  "West Bengal",
];

export const city = [
  [
    "Port Blair",
    "Car Nicobar",
    "Diglipur",
    "Mayabunder",
    "Rangat",
    "Hut Bay",
    "Campbell Bay",
    "Neil Island",
    "Havelock Island",
  ],
  [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kakinada",
    "Kadapa",
    "Eluru",
    "Anantapur",
    "Vizianagaram",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Proddatur",
    "Chittoor",
    "Hindupur",
    "Bhimavaram",
    "Madanapalle",
    "Srikakulam",
    "Anakapalle",
    "Tadepalligudem",
    "Dharmavaram",
    "Gudivada",
    "Narasaraopet",
    "Tadipatri",
    "Kavali",
    "Palasa-Kasibugga",
    "Chirala",
    "Bapatla",
    "Rayachoti",
    "Sullurpeta",
    "Tanuku",
    "Guntakal",
    "Hindupur",
    "Markapur",
    "Amalapuram",
  ],
  [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Tezu",
    "Bomdila",
    "Ziro",
    "Along",
    "Roing",
    "Aalo",
    "Daporijo",
    "Namsai",
    "Yingkiong",
    "Khonsa",
    "Seppa",
    "Palin",
    "Dirang",
    "Changlang",
    "Sagalee",
    "Anini",
  ],
  [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Goalpara",
    "Karimganj",
    "Hailakandi",
    "Sivasagar",
    "North Lakhimpur",
    "Dhubri",
    "Diphu",
    "Golaghat",
    "Barpeta",
    "Haflong",
    "Kokrajhar",
    "Dhemaji",
    "Mangaldoi",
    "Hojai",
    "Nalbari",
    "Lanka",
    "Morigaon",
    "Lumding",
    "Pathsala",
    "Rangia",
    "Moranhat",
    "Sonari",
  ],
  [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Arrah",
    "Bihar Sharif",
    "Katihar",
    "Munger",
    "Purnia",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri",
    "Bettiah",
    "Motihari",
    "Bagaha",
    "Siwan",
    "Kishanganj",
    "Jamalpur",
    "Buxar",
    "Jehanabad",
    "Aurangabad",
    "Lakhisarai",
    "Nawada",
    "Madhubani",
    "Sitamarhi",
    "Samastipur",
    "Begusarai",
    "Rohtas",
    "Arwal",
    "Supaul",
    "Sheikhpura",
    "Mokama",
    "Jamui",
    "Gopalganj",
    "Banka",
    "Munger",
    "Jehanabad",
    "Lakhisarai",
    "Madhepura",
    "Saharsa",
    "Supaul",
    "Sheohar",
    "Araria",
    "Kaimur (Bhabua)",
    "Sheohar",
    "Kaimur (Bhabua)",
  ],
  ["Chandigarh"],
  [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Durg",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Rajnandgaon",
    "Chirmiri",
    "Kawardha",
    "Baikunthpur",
    "Champa",
    "Dhamtari",
    "Mahasamund",
    "Bhatapara",
    "Balod",
    "Kirandul",
    "Manendragarh",
    "Saraipali",
    "Balodabazar",
    "Jagdalpur",
    "Bemetara",
    "Kanker",
    "Basna",
    "Kondagaon",
    "Surajpur",
    "Dalli-Rajhara",
    "Bhilai Charoda",
    "Balrampur",
    "Dongargarh",
    "Narayanpur",
    "Pandariya",
    "Arang",
    "Gobra Nawapara",
    "Takhatpur",
    "Lormi",
    "Pathalgaon",
    "Sonhat",
    "Khairagarh",
    "Kharod",
    "Tilda Newra",
    "Gaurella",
    "Kumhari",
    "Marwahi",
  ],
  [
    "Silvassa",
    "Daman",
    "Diu",
    "Amli",
    "Khanvel",
    "Randha",
    "Nani Daman",
    "Moti Daman",
  ],
  [
    "New Delhi",
    "Rohini",
    "Dwarka",
    "Karol Bagh",
    "Connaught Place",
    "Pitampura",
    "Vasant Kunj",
    "Saket",
    "Laxmi Nagar",
    "Shahdara",
    "Rajouri Garden",
    " Mayur Vihar",
  ],
  [
    "Panaji",
    "Vasco da Gama",
    "Margao (Madgaon)",
    "Mapusa",
    "Ponda",
    "Calangute",
    "Candolim",
    "Bicholim",
    "Sanquelim",
    "Valpoi",
    "Curchorem-Cacora",
    "Quepem",
    "Sanguem",
    "Cuncolim",
    "Davorlim",
    "Canacona",
    "Sattari",
    "Dabolim",
    "Colva",
    "Benaulim",
  ],
  [
    "Ahmedabad",
    "Surat",
    "Vadodara (Baroda)",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Nadiad",
    "Anand",
    "Morbi",
    "Surendranagar",
    "Gandhidham",
    "Veraval",
    "Navsari",
    "Bharuch",
    "Vapi",
    "Porbandar",
    "Botad",
    "Godhra",
    "Valsad",
    "Amreli",
    "Bhuj",
    "Palanpur",
    "Ankleshwar",
    "Deesa",
    "Mehsana",
    "Himatnagar",
    "Dahod",
    "Visnagar",
    "Vyara",
    "Kadi",
    "Modasa",
    "Palitana",
    "Navagam Ghed",
    "Bhachau",
    "Dhoraji",
    "Upleta",
    "Wadhwan",
    "Petlad",
    "Keshod",
    "Khambhat",
    "Kapadvanj",
    "Una",
    "Padra",
    "Gandhavi",
    "Jetpur Navagadh",
    "Kalol",
    "Thangadh",
    "Rajpipla",
  ],
  [
    "Ambala",
    "Yamunanagar",
    "Hisar",
    "Karnal",
    "Panchkula",
    "Panipat",
    "Rohtak",
    "Gurugram ",
    "Faridabad",
    "Sonipat",
    "Rewari",
    "Palwal",
    "Bhiwani",
    "Jind",
    "Kaithal",
    "Kurukshetra",
    "Sirsa",
    "Fatehabad",
    "Bahadurgarh",
    "Charkhi Dadri",
    "Tohana",
    "Narnaul",
    "Hansi",
    "Thanesar",
    "Pinjore",
    "Gohana",
    "Jhajjar",
    "Narwana",
    "Mandi Dabwali",
    "Shahbad",
    "Fatehgarh Sahib",
    "Safidon",
    "Samalkha",
    "Palwal",
    "Kalka",
    "Hathin",
    "Rania",
    "Kosli",
  ],
  [
    "Shimla",
    "Manali",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Kullu",
    "Palampur",
    "Chamba",
    "Bilaspur",
    "Hamirpur",
    "Una",
    "Nahan",
    "Parwanoo",
    "Paonta Sahib",
    "Kangra",
    "Dalhousie",
    "Kasauli",
    "Rampur",
    "Kinnaur",
    "Lahaul and Spiti",
  ],
  [
    "Jammu",
    "Udhampur",
    "Kathua",
    "Rajouri",
    "Poonch",
    "Samba",
    "Reasi",
    "Doda",
    "Kishtwar",
    "Ramban",
    "Srinagar",
    "Anantnag",
    "Baramulla",
    "Sopore",
    "Kupwara",
    "Pulwama",
    "Shopian",
    "Bandipora",
    "Budgam",
    "Ganderbal",
  ],
  [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Ramgarh",
    "Dumka",
    "Medininagar (Daltonganj)",
    "Phusro",
    "Chirkunda",
    "Sahibganj",
    "Godda",
    "Gumla",
    "Madhupur",
    "Jamtara",
    "Garhwa",
    "Simdega",
    "Pakur",
    "Koderma",
    "Chaibasa",
    "Latehar",
    "Jhumri Telaiya",
    "Lohardaga",
    "Chakradharpur",
    "Chatra",
    "Sahebganj",
    "Hazaribagh Town",
    "Sindri",
  ],

  [
    "Bangalore",
    "Mysore ",
    "Hubli-Dharwad",
    "Mangalore ",
    "Belgaum",
    "Gulbarga ",
    "Davanagere",
    "Bellary ",
    "Vijayapura ",
    "Shimoga ",
    "Tumkur ",
    "Raichur",
    "Bidar",
    "Hospet",
    "Hassan",
    "Gadag-Betigeri",
    "Chitradurga",
    "Udupi",
    "Chikmagalur",
    "Mandya",
    "Bagalkot",
    "Kolar",
    "Sirsi",
    "Karwar",
    "Sindhanur",
    "Krishnarajpet",
    "Ramanagara",
    "Gokak",
    "Yadgir",
    "Bhadravati",
    "Chamarajanagar",
    "Koppal",
    "Gangavathi",
    "Sira",
    "Shahabad",
    "Athni",
    "Mulbagal",
    "Malur",
    "Arsikere",
    "Ranebennuru",
  ],
  [
    "Thiruvananthapuram",
    "Kochi (Cochin)",
    "Kozhikode (Calicut)",
    "Thrissur (Trichur)",
    "Kollam (Quilon)",
    "Palakkad (Palghat)",
    "Alappuzha (Alleppey)",
    "Kannur (Cannanore)",
    "Kottayam",
    "Kasaragod",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Ernakulam",
    "Ponnani",
    "Thalassery",
    "Nilambur",
    "Ottappalam",
    "Vadakara",
  ],
  ["Leh", "Kargil", "Diskit", "Nubra", "Dras", "Turtuk", "Padum", "Choglamsar"],
  [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kadmat",
    "Kalpeni",
    "Chetlat",
    "Kiltan",
    "Bitra",
  ],

  [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara (Katni)",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
    "Chhatarpur",
    "Damoh",
    "Mandsaur",
    "Khargone",
    "Neemuch",
    "Pithampur",
    "Sehore",
    "Betul",
    "Hoshangabad",
    "Datia",
    "Nagda",
    "Itarsi",
    "Seoni",
    "Shajapur",
    "Gadarwara",
    "Ashoknagar",
    "Bina",
    "Harda",
    "Rajgarh",
    "Narwar",
    "Badnawar",
    "Mhow",
    "Khategaon",
    "Shahdol",
    "Umaria",
    "Mandla",
    "Dhar",
    "Seoni Malwa",
    "Sanawad",
    "Panna",
  ],
  [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Navi Mumbai",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Miraj",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalna",
    "Bhusawal",
    "Nanded",
    "Satara",
    "Beed",
    "Yavatmal",
    "Panvel",
    "Malegaon",
    "Wardha",
    "Sangamner",
    "Gondia",
    "Hingoli",
    "Ratnagiri",
    "Osmanabad",
    "Nandurbar",
    "Wani",
    "Amalner",
    "Achalpur",
    "Pandharpur",
    "Shrirampur",
    "Parli",
    "Gondiya",
    "Bhiwandi",
    "Nanded Waghala",
    "Bhadravati",
    "Chiplun",
    "Karad",
    "Barsi",
    "Udgir",
    "Lonavala",
  ],
  [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Kakching",
    "Ukhrul",
    "Senapati",
    "Tamenglong",
    "Moirang",
    "Wangjing",
    "Mayang Imphal",
    "Lilong",
    "Kwakta",
    "Jiribam",
    "Moreh",
  ],
  [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongstoin",
    "Baghmara",
    "Resubelpara",
    "Williamnagar",
    "Nongpoh",
    "Khliehriat",
    "Mairang",
    "Nongthymmai",
    "Mawlai",
    "Sohra (Cherrapunji)",
    "Amlarem",
    "Mawkyrwat",
    "Mawphlang",
    "Dawki",
    "Ranikor",
    "Mawthengkut",
    "Rajabala",
  ],
  [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Lawngtlai",
    "Mamit",
    "Saitual",
    "Khawzawl",
    "Hnahthial",
    "Thenzawl",
    "Biate",
    "Bilkhawthlir",
    "North Vanlaiphai",
    "Tlabung",
    "Tlungvel",
    "Darlawn",
    "Phuldungsei",
    "Zawlnuam",
  ],
  [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek",
    "Mon",
    "Longleng",
    "Peren",
    "Kiphire",
    "Tseminyu",
  ],
  [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Brahmapur ",
    "Puri",
    "Sambalpur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jharsuguda",
    "Bargarh",
    "Jeypore",
    "Balangir",
    "Bhawanipatna",
    "Rayagada",
    "Dhenkanal",
    "Anugul",
    "Kendujhar",
    "Jagatsinghpur",
    "Nayagarh",
    "Paradeep",
    "Malkangiri",
    "Nabarangpur",
    "Kendrapara",
    "Sunabeda",
    "Koraput",
    "Phulbani (Kandhamal)",
    "Jatni",
    "Barbil",
    "Athagarh",
  ],
  [
    "Puducherry",
    "Villianur",
    "Bahour",
    "Karaikal",
    "Thirunallar",
    "Mahe",
    "Palloor",
    "Yanam",
  ],
  [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Mohali",
    "Pathankot",
    "Moga",
    "Batala",
    "Abohar",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar",
    "Barnala",
    "Rajpura",
    "Firozpur",
    "Kapurthala",
    "Sangrur",
    "Faridkot",
    "Gurdaspur",
    "Fatehgarh Sahib",
    "Mansa",
    "Fazilka",
    "Ropar (Rupnagar)",
    "Nawanshahr",
    "Tarn Taran",
    "Malout",
    "Nakodar",
  ],
  [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sri Ganganagar",
    "Pali",
    "Sikar",
    "Tonk",
    "Kishangarh",
    "Hanumangarh",
    "Jaisalmer",
    "Nagaur",
    "Churu",
    "Sawai Madhopur",
    "Bundi",
    "Jhalawar",
    "Baran",
    "Chittorgarh",
    "Dausa",
    "Jhunjhunu",
    "Dholpur",
    "Banswara",
    "Barmer",
    "Karauli",
    "Sirohi",
    "Pratapgarh",
    "Dungarpur",
    "Rajsamand",
    "Sirohi",
    "Barmer",
    "Hanumangarh",
    "Jalore",
    "Pratapgarh",
    "Tonk",
    "Chittorgarh",
  ],
  [
    "Gangtok",
    "Namchi",
    "Mangan",
    "Jorethang",
    "Rangpo",
    "Singtam",
    "Gyalshing",
    "Ravangla",
    "Yuksom",
    "Chungthang",
    "Lachen",
    "Lachung",
    "Phodong",
    "Kabi",
    "Pakyong",
    "Aritar",
    "Tadong",
    "Naya Bazaar",
    "Rhenock",
    "Soreng",
    "Bermiok",
    "Rinchenpong",
    "Dzongu",
    "Martam",
    "Hee Bermiok",
    "Rolep",
    "Sakyong-Pentong",
    "Legship",
    "Lingtam",
    "Tumlong",
  ],
  [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Tirunelveli",
    "Thanjavur",
    "Dindigul",
    "Cuddalore",
    "Kanchipuram",
    "Karur",
    "Namakkal",
    "Dharmapuri",
    "Kumbakonam",
    "Nagapattinam",
    "Tiruvannamalai",
    "Hosur",
    "Nagercoil",
    "Pollachi",
    "Rajapalayam",
    "Virudhunagar",
    "Sivakasi",
    "Pudukkottai",
    "Krishnagiri",
    "Ambur",
    "Mayiladuthurai",
    "Karaikudi",
    "Neyveli",
    "Ranipet",
    "Villupuram",
    "Thiruvarur",
    "Udhagamandalam",
    "Thiruvallur",
    "Thiruvottiyur",
    "Arakkonam",
    "Pallavaram",
    "Tirupathur",
    "Ramanathapuram",
    "Thiruvarur",
    "Tenkasi",
    "Perambalur",
  ],
  [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Mancherial",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Siddipet",
    "Miryalaguda",
    "Jagtial",
    "Nirmal",
    "Kamareddy",
    "Bodhan",
    "Armur",
    "Bhadrachalam",
    "Wanaparthy",
    "Gadwal",
    "Sangareddy",
    "Vikarabad",
    "Peddapalli",
    "Jaggaiahpeta",
    "Godavarikhani",
    "Sircilla",
    "Kothagudem",
    "Tandur",
    "Palwancha",
    "Nagarkurnool",
    "Tandur",
    "Jangaon",
    "Bellampalle",
    "Achampet",
    "Asifabad",
    "Bhongir",
    "Boduppal",
    "Chennur",
    "Devarakonda",
    "Domakonda",
    "Gajwel",
    "Huzurabad",
    "Ibrahimpatnam",
    "Jangaon",
    "Kaghaznagar",
    "Kallur",
    "Koratla",
    "Kyathampalle",
    "Mahabubabad",
    "Manuguru",
    "Medak",
    "Metpally",
    "Mulug",
    "Nakrekal",
    "Narayanpet",
    "Narsampet",
    "Peddapalli",
    "Rajanna Sircilla",
    "Sangareddy",
    "Sarapaka",
    "Siricilla",
    "Suryapet",
    "Tandur",
    "Vikarabad",
    "Wanaparthy",
    "Warangal",
  ],
  [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Ambassa",
    "Kailasahar",
    "Belonia",
    "Sonamura",
    "Santirbazar",
    "Sabroom",
    "Kamalpur",
    "Khowai",
    "Amarpur",
    "Bishalgarh",
    "Teliamura",
  ],
  [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi ",
    "Meerut",
    "Prayagraj ",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Ayodhya",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Hapur",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Fatehpur",
    "Rae Bareli",
    "Khora, Ghaziabad",
    "Orai",
    "Bahraich",
    "Unnao",
    "Lakhimpur",
    "Sitapur",
    "Bahadurgarh",
    "Gonda",
    "Banda",
    "Pilibhit",
    "Ghazipur",
    "Jaunpur",
    "Amethi",
    "Deoria",
    "Barabanki",
    "Sultanpur",
    "Basti",
    "Mau",
    "Azamgarh",
    "Tanda",
    "Greater Noida",
    "Sahaswan",
  ],
  [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Ramnagar",
    "Kichha",
    "Sitarganj",
    "Kotdwara",
    "Jaspur",
    "Vikasnagar",
    "Bageshwar",
    "Pithoragarh",
    "Almora",
    "Mussoorie",
    "Ranikhet",
    "Champawat",
    "Khatima",
    "Tanakpur",
    "Doiwala",
    "Chamba",
    "Joshimath",
    "Barkot",
    "Gangotri",
    "Yamunotri",
    "Uttarkashi",
    "Rudraprayag",
    "Karnaprayag",
    "Badrinath",
    "Kedarnath",
    "Pauri",
    "Lansdowne",
    "Tehri",
  ],
  [
    "Kolkata ",
    "Asansol",
    "Siliguri",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Raiganj",
    "Krishnanagar",
    "Naihati",
    "Cooch Behar",
    "Jalpaiguri",
    "Alipurduar",
    "Purulia",
    "Balurghat",
    "Bongaon",
    "Darjeeling",
    "Basirhat",
    "Bankura",
    "Barasat",
    "Medinipur",
    "Rampurhat",
    "Kalyani",
  ],
];

//Districts
export const District = [
[
  "Nicobars",
  "North And Middle Andaman",
  "South Andamans"
],
[
  "Alluri Sitharama Raju",
  "Anakapalli",
  "Ananthapuramu",
  "Annamayya",
  "Bapatla",
  "Chittoor",
  "Dr. B.R. Ambedkar Konaseema",
  "East Godavari",
  "Eluru",
  "Guntur",
  "Kakinada",
  "Krishna",
  "Kurnool",
  "Nandyal",
  "Ntr",
  "Palnadu",
  "Parvathipuram Manyam",
  "Prakasam",
  "Sri Potti Sriramulu Nellore",
  "Sri Sathya Sai",
  "Srikakulam",
  "Tirupati",
  "Visakhapatnam",
  "Vizianagaram",
  "West Godavari",
  "Y.S.R."
],
[
  "Anjaw",
  "Bichom",
  "Changlang",
  "Dibang Valley",
  "East Kameng",
  "East Siang",
  "Kamle",
  "Keyi Panyor",
  "Kra Daadi",
  "Kurung Kumey",
  "Leparada",
  "Lohit",
  "Longding",
  "Lower Dibang Valley",
  "Lower Siang",
  "Lower Subansiri",
  "Namsai",
  "Pakke Kessang",
  "Papum Pare",
  "Shi Yomi",
  "Siang",
  "Tawang",
  "Tirap",
  "Upper Siang",
  "Upper Subansiri",
  "West Kameng",
  "West Siang"
],
[
  "Bajali",
  "Baksa",
  "Barpeta",
  "Biswanath",
  "Bongaigaon",
  "Cachar",
  "Charaideo",
  "Chirang",
  "Darrang",
  "Dhemaji",
  "Dhubri",
  "Dibrugarh",
  "Dima Hasao",
  "Goalpara",
  "Golaghat",
  "Hailakandi",
  "Hojai",
  "Jorhat",
  "Kamrup",
  "Kamrup Metro",
  "Karbi Anglong",
  "Karimganj",
  "Kokrajhar",
  "Lakhimpur",
  "Majuli",
  "Marigaon",
  "Nagaon",
  "Nalbari",
  "Sivasagar",
  "Sonitpur",
  "South Salmara Mancachar",
  "Tamulpur",
  "Tinsukia",
  "Udalguri",
  "West Karbi Anglong"
],
[
  "Araria",
  "Arwal",
  "Aurangabad",
  "Banka",
  "Begusarai",
  "Bhagalpur",
  "Bhojpur",
  "Buxar",
  "Darbhanga",
  "Gaya",
  "Gopalganj",
  "Jamui",
  "Jehanabad",
  "Kaimur (Bhabua)",
  "Katihar",
  "Khagaria",
  "Kishanganj",
  "Lakhisarai",
  "Madhepura",
  "Madhubani",
  "Munger",
  "Muzaffarpur",
  "Nalanda",
  "Nawada",
  "Pashchim Champaran",
  "Patna",
  "Purbi Champaran",
  "Purnia",
  "Rohtas",
  "Saharsa",
  "Samastipur",
  "Saran",
  "Sheikhpura",
  "Sheohar",
  "Sitamarhi",
  "Siwan",
  "Supaul",
  "Vaishali"
],
["Chandigarh "],
[
  "Balod",
  "Balodabazar-Bhatapara",
  "Balrampur-Ramanujganj",
  "Bastar",
  "Bemetara",
  "Bijapur",
  "Bilaspur",
  "Dakshin Bastar Dantewada",
  "Dhamtari",
  "Durg",
  "Gariyaband",
  "Gaurela-Pendra-Marwahi",
  "Janjgir-Champa",
  "Jashpur",
  "Kabeerdham",
  "Khairagarh-Chhuikhadan-Gandai",
  "Kondagaon",
  "Korba",
  "Korea",
  "Mahasamund",
  "Manendragarh-Chirmiri-Bharatpur(M C B)",
  "Mohla-Manpur-Ambagarh Chouki",
  "Mungeli",
  "Narayanpur",
  "Raigarh",
  "Raipur",
  "Rajnandgaon",
  "Sakti",
  "Sarangarh-Bilaigarh",
  "Sukma",
  "Surajpur",
  "Surguja",
  "Uttar Bastar Kanker"
],
[
  "Dadra And Nagar Haveli",
  "Daman",
  "Diu"
],
[
  "Central",
  "East",
  "New Delhi",
  "North",
  "North East",
  "North West",
  "Shahdara",
  "South",
  "South East",
  "South West",
  "West"
],
[
  "North Goa",
  "South Goa"
],
[
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Arvalli",
  "Banas Kantha",
  "Bharuch",
  "Bhavnagar",
  "Botad",
  "Chhotaudepur",
  "Dahod",
  "Dangs",
  "Devbhumi Dwarka",
  "Gandhinagar",
  "Gir Somnath",
  "Jamnagar",
  "Junagadh",
  "Kachchh",
  "Kheda",
  "Mahesana",
  "Mahisagar",
  "Morbi",
  "Narmada",
  "Navsari",
  "Panch Mahals",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabar Kantha",
  "Surat",
  "Surendranagar",
  "Tapi",
  "Vadodara",
  "Valsad"
],
[
  "Ambala",
  "Bhiwani",
  "Charkhi Dadri",
  "Faridabad",
  "Fatehabad",
  "Gurugram",
  "Hisar",
  "Jhajjar",
  "Jind",
  "Kaithal",
  "Karnal",
  "Kurukshetra",
  "Mahendragarh",
  "Nuh",
  "Palwal",
  "Panchkula",
  "Panipat",
  "Rewari",
  "Rohtak",
  "Sirsa",
  "Sonipat",
  "Yamunanagar"
],
[
  "Bilaspur",
  "Chamba",
  "Hamirpur",
  "Kangra",
  "Kinnaur",
  "Kullu",
  "Lahaul And Spiti",
  "Mandi",
  "Shimla",
  "Sirmaur",
  "Solan",
  "Una"
],
[
  "Anantnag",
  "Bandipora",
  "Baramulla",
  "Budgam",
  "Doda",
  "Ganderbal",
  "Jammu",
  "Kathua",
  "Kishtwar",
  "Kulgam",
  "Kupwara",
  "Poonch",
  "Pulwama",
  "Rajouri",
  "Ramban",
  "Reasi",
  "Samba",
  "Shopian",
  "Srinagar",
  "Udhampur"
],
[
  "Bokaro",
  "Chatra",
  "Deoghar",
  "Dhanbad",
  "Dumka",
  "East Singhbum",
  "Garhwa",
  "Giridih",
  "Godda",
  "Gumla",
  "Hazaribagh",
  "Jamtara",
  "Khunti",
  "Koderma",
  "Latehar",
  "Lohardaga",
  "Pakur",
  "Palamu",
  "Ramgarh",
  "Ranchi",
  "Sahebganj",
  "Saraikela Kharsawan",
  "Simdega",
  "West Singhbhum"
],
[
  "Bagalkote",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bidar",
  "Chamarajanagar",
  "Chikkaballapura",
  "Chikkamagaluru",
  "Chitradurga",
  "Dakshina Kannada",
  "Davanagere",
  "Dharwad",
  "Gadag",
  "Hassan",
  "Haveri",
  "Kalaburagi",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru",
  "Raichur",
  "Ramanagara",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vijayanagara",
  "Vijayapura",
  "Yadgir"
],
[
  "Alappuzha",
  "Ernakulam",
  "Idukki",
  "Kannur",
  "Kasaragod",
  "Kollam",
  "Kottayam",
  "Kozhikode",
  "Malappuram",
  "Palakkad",
  "Pathanamthitta",
  "Thiruvananthapuram",
  "Thrissur",
  "Wayanad"
],
[
  "Kargil",
  "Leh Ladakh"
],
["Lakshadweep District"],
[
  "Agar-Malwa", 
  "Alirajpur", 
  "Anuppur", 
  "Ashoknagar", 
  "Balaghat", 
  "Barwani", 
  "Betul", 
  "Bhind", 
  "Bhopal", 
  "Burhanpur", 
  "Chhatarpur", 
  "Chhindwara", 
  "Damoh", 
  "Datia", 
  "Dewas", 
  "Dhar", 
  "Dindori", 
  "Guna", 
  "Gwalior", 
  "Harda", 
  "Indore", 
  "Jabalpur", 
  "Jhabua", 
  "Katni", 
  "Khandwa (East Nimar)", 
  "Khargone (West Nimar)", 
  "MAUGANJ", 
  "Maihar", 
  "Mandla", 
  "Mandsaur", 
  "Morena", 
  "Narmadapuram", 
  "Narsimhapur", 
  "Neemuch", 
  "Niwari", 
  "Pandhurna", 
  "Panna", 
  "Raisen", 
  "Rajgarh", 
  "Ratlam", 
  "Rewa", 
  "Sagar", 
  "Satna", 
  "Sehore", 
  "Seoni", 
  "Shahdol", 
  "Shajapur", 
  "Sheopur", 
  "Shivpuri", 
  "Sidhi", 
  "Singrauli", 
  "Tikamgarh", 
  "Ujjain", 
  "Umaria", 
  "Vidisha"
],
[
  "Ahilyanagar", 
  "Akola", 
  "Amravati", 
  "Beed", 
  "Bhandara", 
  "Buldhana", 
  "Chandrapur", 
  "Chhatrapati Sambhajinagar", 
  "Dharashiv", 
  "Dhule", 
  "Gadchiroli", 
  "Gondia", 
  "Hingoli", 
  "Jalgaon", 
  "Jalna", 
  "Kolhapur", 
  "Latur", 
  "Mumbai", 
  "Mumbai Suburban", 
  "Nagpur", 
  "Nanded", 
  "Nandurbar", 
  "Nashik", 
  "Palghar", 
  "Parbhani", 
  "Pune", 
  "Raigad", 
  "Ratnagiri", 
  "Sangli", 
  "Satara", 
  "Sindhudurg", 
  "Solapur", 
  "Thane", 
  "Wardha", 
  "Washim", 
  "Yavatmal"
],
[
  "Bishnupur", 
  "Chandel", 
  "Churachandpur", 
  "Imphal East", 
  "Imphal West", 
  "Jiribam", 
  "Kakching", 
  "Kamjong", 
  "Kangpokpi", 
  "Noney", 
  "Pherzawl", 
  "Senapati", 
  "Tamenglong", 
  "Tengnoupal", 
  "Thoubal", 
  "Ukhrul"
],
[
  "East Garo Hills", 
  "East Jaintia Hills", 
  "East Khasi Hills", 
  "Eastern West Khasi Hills", 
  "North Garo Hills", 
  "Ri Bhoi", 
  "South Garo Hills", 
  "South West Garo Hills", 
  "South West Khasi Hills", 
  "West Garo Hills", 
  "West Jaintia Hills", 
  "West Khasi Hills"
],
[
  "Aizawl", 
  "Champhai", 
  "Hnahthial", 
  "Khawzawl", 
  "Kolasib", 
  "Lawngtlai", 
  "Lunglei", 
  "Mamit", 
  "Saitual", 
  "Serchhip", 
  "Siaha"
],
[
  "Chumoukedima", 
  "Dimapur", 
  "Kiphire", 
  "Kohima", 
  "Longleng", 
  "Mokokchung", 
  "Mon", 
  "Niuland", 
  "Noklak", 
  "Peren", 
  "Phek", 
  "Shamator", 
  "Tseminyu", 
  "Tuensang", 
  "Wokha", 
  "Zunheboto"
],
[
  "Anugul", 
  "Balangir", 
  "Baleshwar", 
  "Bargarh", 
  "Bhadrak", 
  "Boudh", 
  "Cuttack", 
  "Deogarh", 
  "Dhenkanal", 
  "Gajapati", 
  "Ganjam", 
  "Jagatsinghapur", 
  "Jajapur", 
  "Jharsuguda", 
  "Kalahandi", 
  "Kandhamal", 
  "Kendrapara", 
  "Kendujhar", 
  "Khordha", 
  "Koraput", 
  "Malkangiri", 
  "Mayurbhanj", 
  "Nabarangpur", 
  "Nayagarh", 
  "Nuapada", 
  "Puri", 
  "Rayagada", 
  "Sambalpur", 
  "Sonepur", 
  "Sundargarh"
],
[
  "Karaikal",
  "Puducherry"
],
[
  "Amritsar",
  "Barnala",
  "Bathinda",
  "Faridkot",
  "Fatehgarh Sahib",
  "Fazilka",
  "Ferozepur",
  "Gurdaspur",
  "Hoshiarpur",
  "Jalandhar",
  "Kapurthala",
  "Ludhiana",
  "Malerkotla",
  "Mansa",
  "Moga",
  "Pathankot",
  "Patiala",
  "Rupnagar",
  "S.A.S Nagar",
  "Sangrur",
  "Shahid Bhagat Singh Nagar",
  "Sri Muktsar Sahib",
  "Tarn Taran"
],
[
  "Ajmer",
  "Alwar",
  "Balotra",
  "Banswara",
  "Baran",
  "Barmer",
  "Beawar",
  "Bharatpur",
  "Bhilwara",
  "Bikaner",
  "Bundi",
  "Chittorgarh",
  "Churu",
  "Dausa",
  "Deeg",
  "Dholpur",
  "Didwana-Kuchaman",
  "Dungarpur",
  "Ganganagar",
  "Hanumangarh",
  "Jaipur",
  "Jaisalmer",
  "Jalore",
  "Jhalawar",
  "Jhunjhunu",
  "Jodhpur",
  "Karauli",
  "Khairthal-Tijara",
  "Kota",
  "Kotputli-Behror",
  "Nagaur",
  "Pali",
  "Phalodi",
  "Pratapgarh",
  "Rajsamand",
  "Salumbar",
  "Sawai Madhopur",
  "Sikar",
  "Sirohi",
  "Tonk",
  "Udaipur"
],
[
  "Gangtok",
  "Gyalshing",
  "Mangan",
  "Namchi",
  "Pakyong",
  "Soreng"
],
[
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kancheepuram",
  "Kanniyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvannamalai",
  "The Nilgiris",
  "Theni",
  "Thiruvallur",
  "Thiruvarur",
  "Thoothukkudi",
  "Vellore",
  "Viluppuram",
  "Virudhunagar"
],
[
  "Adilabad",
  "Bhadradri Kothagudem",
  "Hanumakonda",
  "Hyderabad",
  "Jagitial",
  "Jangoan",
  "Jayashankar Bhupalapally",
  "Jogulamba Gadwal",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Kumuram Bheem Asifabad",
  "Mahabubabad",
  "Mahabubnagar",
  "Mancherial",
  "Medak",
  "Medchal Malkajgiri",
  "Mulugu",
  "Nagarkurnool",
  "Nalgonda",
  "Narayanpet",
  "Nirmal",
  "Nizamabad",
  "Peddapalli",
  "Rajanna Sircilla",
  "Ranga Reddy",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Wanaparthy",
  "Warangal",
  "Yadadri Bhuvanagiri"
],
[
  "Dhalai",
  "Gomati",
  "Khowai",
  "North Tripura",
  "Sepahijala",
  "South Tripura",
  "Unakoti",
  "West Tripura"
],
[
  "Agra",
  "Aligarh",
  "Ambedkar Nagar",
  "Amethi",
  "Amroha",
  "Auraiya",
  "Ayodhya",
  "Azamgarh",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Bara Banki",
  "Bareilly",
  "Basti",
  "Bhadohi",
  "Bijnor",
  "Budaun",
  "Bulandshahr",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar",
  "Ghaziabad",
  "Hardoi",
  "Hathras",
  "Jalaun",
  "Jaunpur",
  "Jhansi",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kasganj",
  "Kaushambi",
  "Kheri",
  "Kushinagar",
  "Lalitpur",
  "Lucknow",
  "Mahoba",
  "Mahrajganj",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Prayagraj",
  "Rae Bareli",
  "Rampur",
  "Saharanpur",
  "Sambhal",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi",
  "Sant Kabir Nagar",
  "Shahjahanpur",
  "Shamli",
  "Shrawasti",
  "Siddharthnagar"
],
[
  "Almora",
  "Bageshwar",
  "Chamoli",
  "Champawat",
  "Dehradun",
  "Haridwar",
  "Nainital",
  "Pauri Garhwal",
  "Pithoragarh",
  "Rudraprayag",
  "Tehri Garhwal",
  "Udham Singh Nagar",
  "Uttarkashi"
],
[
  "Alipurduar",
  "Bankura",
  "Birbhum",
  "Cooch Behar",
  "Dakshin Dinajpur",
  "Darjeeling",
  "Hooghly",
  "Howrah",
  "Jalpaiguri",
  "Jhargram",
  "Kalimpong",
  "Kolkata",
  "Malda",
  "Murshidabad",
  "Nadia",
  "North 24 Parganas",
  "Paschim Bardhaman",
  "Paschim Medinipur",
  "Purba Bardhaman",
  "Purba Medinipur",
  "Purulia",
  "South 24 Parganas",
  "Uttar Dinajpur"
],

]