const CURR_Appointment_ACTION_TYPE = {
  SET_CURR_RESCHEDULEDATA: "curr_appointment/SET_CURR_RESCHEDULE",
  REMOVE_CURRENT_RESCHEDULE: "REMOVE_CURRENT_RESCHEDULE"
};

export default CURR_Appointment_ACTION_TYPE;
