const ERROR_ACTION_TYPES = {
  SET_ERROR: "error/SET_ERROR",
  SET_SUCCESS: "error/SET_SUCCESS",
  SET_CLOSE: "error/SET_CLOSE",
  SET_LOADING: "loading/SET_LOADING",
  SET_LOADING_CLOSE: "loading/SET_LOADING_CLOSE",
  SET_BACKDROP_LOADING: "loading/SET_LOADING_BACKDROP",
  SET_BACKDROP_LOADING_CLOSE: "loading/SET_LOADING_BACKDROP_CLOSE"
};

export default ERROR_ACTION_TYPES;
